[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[theme]
primaryColor = '#2e7d32'
backgroundColor = '#ffffff'
secondaryBackgroundColor = '#f7fafc'
textColor = '#2d3748'
font = 'sans serif'
